PORT?=/dev/ttyUSB0
PROJECT=benj.cpp
ARDUINO_MODEL=nano
MCU=atmega328p
UPLOAD_RATE=57600
ARDUINO_DIR=${HOME}/Arduino/arduino-1.6.4/
AVR_TOOLS_PATH=${HOME}/Arduino/arduino-1.6.4/hardware/tools/avr/bin/
USER_LIBDIR=${HOME}/Arduino/libraries
USER_LIBS=RadioHead Adafruit_NeoPixel ubberFrame
include Makefile.arduino

